networks:
  fullstack:

volumes:
  mysql:

services:
  proxy:
    image: nginx:1.26-alpine3.19
    depends_on:
      - backend
      - swagger
      - db
      - phpmyadmin
      - jsonserver
      - docs
      - mailcatcher
    networks:
      - fullstack
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
      - ./backend:/www:rw
      # - .env:/www/.env:rw

  backend:
    image: rcsnjszg/backend2024
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/www:rw
      - ./backend/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    networks:
      - fullstack
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: idomi27/vue
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:rw
    networks:
      - fullstack

  db:
    image: mysql:8.0.37
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ=${TZ}
    volumes:
      - "mysql:/var/lib/mysql:rw"
    networks:
      - fullstack
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$DB_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: rcsnjszg/phpmyadmin:5.2.1-apache
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - UPLOAD_LIMIT=300M
    networks:
      - fullstack
  
  docs:
    image: idomi27/nuxt-content:3.11.2
    volumes:
      - ./docs:/app/content:ro
    networks:
      - fullstack

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger/openapi.yaml:/docs/openapi.yaml
    environment:
        - SWAGGER_JSON=/docs/openapi.yaml
    networks:
      - fullstack

  jsonserver:
    image: idomi27/json-server
    build:
      context: ./jsonserver
      dockerfile: Dockerfile
    networks:
      - fullstack
    volumes:
      - ./jsonserver:/app
      - /app/node_modules
  
  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    networks:
      - fullstack